// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6Gn-UmAjY_ArjkxQsEhSSSTdJBpSTXjE',
    appId: '1:849288698640:web:67870346d2f809806ca395',
    messagingSenderId: '849288698640',
    projectId: 'dbaggad-b92fb',
    authDomain: 'dbaggad-b92fb.firebaseapp.com',
    storageBucket: 'dbaggad-b92fb.appspot.com',
    measurementId: 'G-542X8QNVXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiBJ2VCgBqf6oO4zgCjCHBWIYcmRIzU9M',
    appId: '1:849288698640:android:f854ef42b483b2ac6ca395',
    messagingSenderId: '849288698640',
    projectId: 'dbaggad-b92fb',
    storageBucket: 'dbaggad-b92fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT_jpQMUHYpGJcJdgKPx6H2X1iNKvbPCw',
    appId: '1:849288698640:ios:a4fe34ee79aeff716ca395',
    messagingSenderId: '849288698640',
    projectId: 'dbaggad-b92fb',
    storageBucket: 'dbaggad-b92fb.appspot.com',
    iosClientId: '849288698640-off55t6l0f6hsam01ap91emptuc9qns9.apps.googleusercontent.com',
    iosBundleId: 'com.example.aggad',
  );
}
